### ISSUE TITLE
React Native 属性使用

### ISSUE THREAD

**Issue by LengYi** [wuba/Picasso#11]
Sketch 转出来的代码，样式中有嵌套，实际RN是不支持嵌套的，这个你们实际使用是怎么用的呢？
const styles = StyleSheet.create({
     "submit": {
        "textStyle": {
            "lineHeight": scaleSize(22),
            "textAlign": "left",
            "color": {
                "alpha": 1,
                "red": 51,
                "green": 51,
                "blue": 51
            },
            "fontSize": scaleSize(16),
            "fontFamily": "Avenir-Medium",
            "fontWeight": 500
        },
        "marginTop": scaleSize(-23)
    }
})

**Comment by huangwencun** [comment]
应该是bug，近期会修复

**Comment by iChengbo** [comment]
@LengYi  方便提供下 sketch 文件吗？

**Comment by LengYi** [comment]
可以，加Q 707689817@qq.com

**Comment by LengYi** [comment]
目前你们的转换成功率有多少呢

**Comment by iChengbo** [comment]
> 可以，加Q [707689817@qq.com](mailto:707689817@qq.com)

已加，有时间时文件发我一下，我看看

**Comment by huangwencun** [comment]
> 目前你们的转换成功率有多少呢

80%左右，可以扫码加微信群交流哈

**Comment by LengYi** [comment]
码在哪里

**Comment by iChengbo** [comment]
> 码在哪里

https://github.com/wuba/Picasso/issues/2

**Comment by LengYi** [comment]
再次过期

**Comment by huangwencun** [comment]
> 再次过期

已更新

**Comment by huangwencun** [comment]
已修复
