### ISSUE TITLE
TypeError：sliceFrame.left is not a function. ( In 'sliceFrame.left()' , 'sliceFrame.left()' is undefine ).

### ISSUE THREAD

**Issue by JackingHuang** [wuba/Picasso#14]
![image](https://user-images.githubusercontent.com/13046337/118615571-73a41080-b7f3-11eb-83af-c6164ed9b129.png)

**Comment by huangwencun** [comment]
方便提供下mac版本及sketch软件版本吗

**Comment by JackingHuang** [comment]
我看了一下，应该不是sRGB IEC61966-2.1 配置的问题，具体的问题等有时间了重新编译插件，抓取具体的日志。

系统： macOS Catalina 10.15.6
Sketch: 72.1(124357)

**Comment by JackingHuang** [comment]
![image](https://user-images.githubusercontent.com/13046337/119215917-3eedcd00-bb03-11eb-8a17-26277296893f.png)

报错提示：
        TypeError：sliceFrame.left is not a function. ( In 'sliceFrame.left()' , 'sliceFrame.left()' is undefine ).

**Comment by huangwencun** [comment]
> ![image](https://user-images.githubusercontent.com/13046337/119215917-3eedcd00-bb03-11eb-8a17-26277296893f.png)
> 
> 报错提示：
> TypeError：sliceFrame.left is not a function. ( In 'sliceFrame.left()' , 'sliceFrame.left()' is undefine ).

该问题已修复，请将插件更新到v2.1.1版本

**Comment by huangwencun** [comment]
问题已修复，请将插件更新至v2.1.1版本
