### ISSUE TITLE
[Feature Request] 直接解析 sketch 文件而不是使用 sketch 插件

### ISSUE THREAD

**Issue by qiwang97** [wuba/Picasso#20]
个人感觉开发更习惯使用代码操作
如果可以直接解析 sketch 文件，可以配合脚本进行自动化操作

[skeditor](https://github.com/skeditor/skeditor) 是使用 jszip 解析 sketch 文件然后借助 skia 将图层使用 canvas 画到网页上。
我看源码部分，很多逻辑是和 sketch 运行环境强相关，没有解耦开，不是很好处理
咱们后续是否有计划支持直接解析 sketch 文件呀？

**Comment by qiwang97** [comment]
https://developer.sketch.com/file-format/ 
参考官方文档，解压之后的 pages 下面是有对应的 json schema 的 这一步应该可以帮助解析文件

**Comment by jumeiyu58** [comment]
很棒的想法，后续会考虑不在依赖sketch环境，支持浏览器直接上传sketch进行解析。后续有进展会及时同步，敬请期待！

**Comment by cbbfcd** [comment]
坐等该特性
