### ISSUE TITLE
交流帖, 打听下你们是如何说服UI按这套规范改图的, 还是拿到 .sketch 后自己修图.

### ISSUE THREAD

**Issue by halo951** [wuba/Picasso#28]
如题

**Comment by SunilWang** [comment]
这个就是协商问题了，只要能整体提效，并且对UI的副作用比较少，那么UI还是容易接受的。

**Comment by halo951** [comment]
我原来试过, 有点难搞~ 最终要不是自己改图, 要不就蓝湖 贴样式了. 上次还给蓝湖提了个建议, 让他们加入点NLP分析逻辑去优化他们的设计稿转代码. 不过后来没信了~
