### ISSUE TITLE
使用master版本，编译picasso-parse后把结果覆盖到@wubafe，结果和编译前不一致

### ISSUE THREAD

**Issue by cc8476** [wuba/Picasso#32]
复现步骤：
1.下载master版本  npm i   (3.9下载)
2.在sketch导出html,可以看到html有多层的树结构（能区分出多个Row）
![image](https://user-images.githubusercontent.com/23565901/223985350-e4240fb5-554e-4764-912c-b6b954988fbc.png)

3.进入picasso-package/packages/picasso-parse
4.npm run tsc 后，把dist内的内容，覆盖到 node_modules/@wubafe/picasso-parse/dist
5.重新导出html,发现不能区分多个Row了

![image](https://user-images.githubusercontent.com/23565901/223985462-d371d3cf-78da-4c74-9011-4df2b0a450cf.png)

怀疑是否原@wubafe内的源代码和master下的代码不一致，求前辈帮忙！
非常感谢！

**Comment by keepGoinging** [comment]
您好，可能是版本引入的不一致导致的，您可以手动更改下，看是否还有这个问题；原因可能是：<img width="420" alt="image" src="https://user-images.githubusercontent.com/71016874/224297392-ca03aed6-1fee-4e98-b7d8-5fe4a04036cc.png">
外层的package.json引用的包是"@wubafe/picasso-parse": "0.0.32"，而进入picasso-package/packages/picasso-parse中的包是 "version": "0.0.40",
<img width="434" alt="image" src="https://user-images.githubusercontent.com/71016874/224297711-19c99662-117e-4a24-96c4-f523b6d909bc.png">

**Comment by cc8476** [comment]
能麻烦再帮忙确认下，0.0.32对应的是git上哪次提交吗？我想找一下源码
在已打包的node_modules里面的0.0.32版本的src里面，只有部分的源码，我想需要
piscasso-code-broswer
piscasso-dsl
piscasso-group
piscasso-layout
piscasso-parse
piscasso-trans
piscasso-dsl
这些目录的代码研究下

感谢感谢！

**Comment by SunilWang** [comment]
@cc8476 clone 项目：Picasso/picasso-package/packages  这个目录下

**Comment by cc8476** [comment]
@SunilWang 你说的是最新版本0.0.40是在这个目录下
我需要0.0.32版本
在该目录下package.json里没有标明version,故从代码层面看不出来

**Comment by BeanBunWang** [comment]
> 能麻烦再帮忙确认下，0.0.32对应的是git上哪次提交吗？我想找一下源码 因为我发现好像0.0.32版本解析的Html结构层次更多一些
> 
> 在已打包的node_modules里面的0.0.32版本的src里面，只有部分的源码，我想需要 piscasso-code-broswer piscasso-dsl piscasso-group piscasso-layout piscasso-parse piscasso-trans piscasso-dsl 这些目录的代码研究下
> 
> 感谢感谢！

这里查看了下，应该是下面的commit中，根目录的@wubafe/picasso-parse版本从0.0.28变成0.0.32，picasso-package/packages/picasso-parse的版本从0.0.30更新为0.0.33（0.0.32是本地打包的并发布的，不过和0.0.33的差异很小）。
希望可以帮到您~

commitId：28d40048b9f99bf6b91d3517578a76b0df3ec2b9
github链接：https://github.com/wuba/Picasso/commit/28d40048b9f99bf6b91d3517578a76b0df3ec2b9

**Comment by cc8476** [comment]
收到，谢谢各位！
